cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = [
        "//revgrad:data",
        "//revgrad:sort",
    ],
)

cc_binary(
    name = "function",
    srcs = ["function.cpp"],
    deps = [
        "//revgrad:data",
    ],
)